### ISSUE TITLE
[Suggestion] Add exception for comments

### ISSUE THREAD

**Issue by pimalel233** [Laike-Endaril/Set-Bonus#13]
Hi,
something like you have done in 18 patch for empty lines so they do not throw errors, maybe do the same for lines that start, for example with #? It's useful to comment sets for refence, but that also spams the log a bit.

**Comment by Laike-Endaril** [comment]
This is now a thing in the latest version (019), but it uses the grave (`) instead of #, because # is more likely to appear in eg. an item name, and I don't feel like messing with escape characters for something this specific
