### ISSUE TITLE
[Suggestion] Third Discovery Mode

### ISSUE THREAD

**Issue by Swigen** [Laike-Endaril/Set-Bonus#14]
Hey, love the mod and think it works great with other rpg style mods. I was curious if you could add a third discovery mode that makes set text invisible, even after equipping all items in the set. When creating sets with only one item, this would allow the potion effects and attribute modifications to trigger as if part of the base item. Also this would prevent having to download other mods and make it doable with the ease of use present in the set bonus configs.

Thanks!

**Comment by Laike-Endaril** [comment]
Not sure when this will happen, but it's not a bad idea, so I'll put it on my TODO list

**Comment by CalaMariGold** [comment]
Oh, this would actually be amazing! However, it would need to be definable per item (can't recall if that's already how it works). So some items have text for set bonuses and others don't.

**Comment by Laike-Endaril** [comment]
This is now added in the latest version

**Comment by SandwichHorror** [comment]
Bless
