### ISSUE TITLE
Attribute-based bonuses do nothing

### ISSUE THREAD

**Issue by vizthex123** [Laike-Endaril/Set-Bonus#16]
It seems like it at least.
I have a few set bonuses that give extra armour and/or armour toughness, but they don't seem to actually be added t o the player.

That, or the bar doesn't render them.

Kind of annoying since it defeats the purpose of the mod....

**Comment by democat3457** [comment]
How are you declaring the attribute-based bonuses? Using the bonus from #15, here's its entry in section 3:
```
IceScaleArmorBonus, generic.armor = 5 @ 0, generic.maxHealth = 10 @ 0
```
(its entry in section 4 is this)
```
IceScaleArmorBonus, minecraft:resistance.1
```

**Comment by Laike-Endaril** [comment]
Aye, attribute bonuses should be working fine.  Here's a basic test/example config file for reference:

[1.12.2.009+.zip](https://github.com/Laike-Endaril/Set-Bonus/files/4974391/1.12.2.009%2B.zip)

I used max health in this example, but armor also renders properly.  Closing this one for now, but if there's still an issue, I'll see any responses here.

**Comment by vizthex123** [comment]
Hmmm...I've only noticed it apply to Armor Toughness, and sometimes armor points itself.

It could be Classic bars not picking up the changes.

Honestly I don't mind if it doesn't render on the HUD as long as it works

**Comment by vizthex123** [comment]
> How are you declaring the attribute-based bonuses? Using the bonus from #15, here's its entry in section 3:
> 
> ```
> IceScaleArmorBonus, generic.armor = 5 @ 0, generic.maxHealth = 10 @ 0
> ```
> 
> (its entry in section 4 is this)
> 
> ```
> IceScaleArmorBonus, minecraft:resistance.1
> ```

Yes that's how I formatted them, the config told me so. I meant that if I change armor toughness for example, it doesn't render on the bar (could be Classic Bars not picking it up though)

Though I have mine formatted as `generic.armor = 4.0 @ 1`, so maybe that's why?
