### ISSUE TITLE
[Suggest] A generic armor bonus

### ISSUE THREAD

**Issue by MokoBlack** [Laike-Endaril/Set-Bonus#2]
When the player stacks the armor to a certain level, it triggers an effect
 ..  in my modpack, high armor value is used as heavy armor, and I need a function that reflects this.but now ，just the weight fit the requirement. so i m thinking about give it shield blocking effect, can do it ?
 Of course, it's not all-round blocking. It's too OP.
If possible, it's just that there's an effective angle in front and behind.

**Comment by Laike-Endaril** [comment]
I might make a status effect that gives a % chance of blocking attacks (higher % for higher potion effect levels) which could be used for this.

Just to be clear, you're also requesting a way to trigger bonuses based on total armor level, right? (Instead of a certain armor set)

**Comment by MokoBlack** [comment]
Yes

**Comment by Laike-Endaril** [comment]
I'm thinking about a system for stat requirements which should cover this.  It would allow you to specify eg. "armor must be at least x", "armor must be less than x", or "attack damage must be at least x", etc.

For vanilla stats, this mostly makes sense for certain ones, like armor.  It would become more useful if you have other mods that add RPG stats like strength, dexterity, wisdom, intelligence, etc.

I just need to figure out the best way of doing it, code-wise.

**Comment by Laike-Endaril** [comment]
This should now be implemented in the latest release (1.12.2.009)
