### ISSUE TITLE
"No armor" requirement?

### ISSUE THREAD

**Issue by democat3457** [Laike-Endaril/Set-Bonus#21]
Is it possible to define a set that requires a lack of armor? For example, I have a set that requires offhand and mainhand items, but I also want to restrict the helm/chest/legs/boots to only no armor and leather.

**Comment by TheGameCreator13** [comment]
You could make a second set bonus that nullifies the first set bonus but that might be cumbersome to type out

For example a bonus for a sword that gives +1 heart but a second bonus that triggers when both a sword and any piece of armor is also worn which gives -1 heart. Nullifying the first set bonus

Limited, but its a workaround

**Comment by democat3457** [comment]
> when both a sword and any piece of armor is also worn

Wellll... not really possible to make in a pack with 300+ mods

**Comment by TheGameCreator13** [comment]
Oh hey I have something that might be a solution actually!
If You look in the **Bonuses** section about requirements:
```
        # Each requirement is one of these:
        # A set; just put in the set id.  For a partial set, add a period and the number of set items required
     -> # an attribute total; put in the attribute name followed by a sign and a number, eg.
        # generic.armor > 7
```
So just have
`generic.armor >= 0`

This will at least disallow wearing equipment that adds armor

**Comment by Laike-Endaril** [comment]
You can actually do this in a direct manner, because...
minecraft:air
...is a real item

Ie. there is no such thing as an empty item slot in MC.  There is always an item in all slots.  The item in an "empty" slot is "air", so you can define an equip using said air to require air in a slot.

Sorry for the late response.

**Comment by TheGameCreator13** [comment]
That's actually kind of hilarious. 😄
You should add that into the config descriptions since most people wouldn't even think to try that.
Really good to know!
