### ISSUE TITLE
[Suggest]Unique set bonus for mob

### ISSUE THREAD

**Issue by MokoBlack** [Laike-Endaril/Set-Bonus#3]
It seems unfair that only players can enjoy rich set additions, especially modpacks with hard core themes. its also fun if mob have their own set effect . 
Besides, I'm experimenting with mob duels in my modpack with other mods.
I give them all some equipment and weapons, but there's no special bonus other than just armor and melee attack.
For vanilla creatures, like Blaze, there is a disadvantage in dueling because its ability to fire fireballs has not provided any beneficial bonus
So. can you create mob-special-set confirm?
This function prepares some abilities in advance. Players only need to make a Set that triggers this ability. When the mob gains the Set, it gains this ability
The ability i think of  is : 
*Enderman-teleporting : just let mob get Enderman's teleporting feature .
*Wither-skull: A mob which have special rang attack (such as Blaze)will summon wither skull when shooting .
*Ghastball: Same as above,will confuse players because looks like normal fireball
*Alchemy: all attack from the  mob can deal poison，（Including the projectile like fireballs）

About other ability ,just do whatever you want to

**Comment by Laike-Endaril** [comment]
Mob abilities are an interesting idea, but are something I'm avoiding for this mod.

I also don't want to implement set bonus detection for mobs, because it will drastically increase the computation needed to do inventory checks.  Sorry!
