### ISSUE TITLE
[BUG] (Un)Stacking Potion Effect Levels Bug

### ISSUE THREAD

**Issue by Rhykes** [Laike-Endaril/Set-Bonus#5]
(Mentioned this in a comment on curseforge, but I figure I might as well replicate it here, too!)

Recent update fixed the Stacking Potion Effect Bug where higher potency enchants overwrote the lowest one until restart, causing any number of set pieces to always give maximum potency.

That fix seems to have introduced a new problem: Losing pieces of a set drops you to the lowest potency bonus until the set is re-equipped.

Like before, I tested with a 2/4 Slowness I, 3/4 Slowness II, and 4/4 Slowness III. Upon equipping 4/4 and then removing 1 piece (3/4), I am incorrectly put at Slowness I which should be tied at 2/4. This is fixed by un-equipping and re-equipping the middle piece, but that's annoying for a user for beneficial buffs and obviously they don't want to re-equip the piece for debuffs.

**Comment by Laike-Endaril** [comment]
Looking into this ASAP

Edit: Bug confirmed

**Comment by Laike-Endaril** [comment]
I've fixed this in my indev version, but I'm going to try to improve one other thing before releasing it.

**Comment by Laike-Endaril** [comment]
This should now be fixed in the latest release (1.12.2.010)
