### ISSUE TITLE
Set Bonus Timer Suggestion

### ISSUE THREAD

**Issue by CalaMariGold** [Laike-Endaril/Set-Bonus#8]
Basically, there are some potion effects that would be great as a set bonus, but because set bonuses apply the potion effect constantly, it would be too OP or wouldn't work.

My suggestion is that there are an extra two parameters in the "Potions" part of the config that makes it so the potion effect lasts for X seconds every Y seconds.

For example, PotionCraft has a potion effect that when applied to the player, all mobs around the player are frozen until the effect wears off.

So, in the config it could look like this: 
```
# every 60 seconds, FreezeAOE is applied for 10 seconds.
ArmorSetBonus, potioncraft.freezeaoe.1, 60, 10
```

This would open up a huge amount of possibilities! I just want to say I absolutely love this mod and it is a huuuuge part of my modpack (we recently got featured!) If you're interested in staying in touch and have some spare time, join our Discord and we can chat: https://discord.gg/VDvJdjR

**Comment by Laike-Endaril** [comment]
TBH my schedule has been jam-packed lately, but as you said, this feature is a good way of balancing out some of the more powerful potion effects, so I'll probably set some time aside and add this.

**Comment by Laike-Endaril** [comment]
This is now implemented in the latest version (017).  See the new potion bonus tooltip for syntax.

And ofc, tell me if you run into any issues
